### ISSUE TITLE
I can't get this to work!

### ISSUE THREAD

**Issue by Klortho** [crosscite/content-negotiation#1]
:)

**Comment by mfenner** [comment]
Haha. Just started this project. Should be working before the end of a month. A replacement for https://github.com/datacite/content-resolver, based on https://github.com/datacite/bolognese.

**Comment by mfenner** [comment]
Now working as staged version: https://data.test.datacite.org. Documentation at http://citation.crosscite.org/docs.html, but do content negotiation directly with this server, e.g. 
```
curl -LH "Accept: text/x-bibliography; style=apa" https://data.test.datacite.org/10.1126/science.169.3946.635
```
