### ISSUE TITLE
DOI content negotiation to CSL JSON returns title=":{unav)"

### ISSUE THREAD

**Issue by dhimmel** [crosscite/content-negotiation#102]
JSON produced by https://data.crosscite.org/application/vnd.citationstyles.csl+json/10.1186/1471-2164-7-187

```json
{
  "type": "article-journal",
  "id": "https://doi.org/10.1186/1471-2164-7-187",
  "author": [
    {
      "family": "Myers",
      "given": "Chad L"
    },
    {
      "family": "Barrett",
      "given": "Daniel R"
    },
    {
      "family": "Hibbs",
      "given": "Matthew A"
    },
    {
      "family": "Huttenhower",
      "given": "Curtis"
    },
    {
      "family": "Troyanskaya",
      "given": "Olga G"
    }
  ],
  "issued": {
    "date-parts": [
      [
        2006
      ]
    ]
  },
  "container-title": "BMC Genomics",
  "DOI": "10.1186/1471-2164-7-187",
  "volume": "7",
  "issue": "1",
  "page": "187",
  "publisher": "Springer Science and Business Media LLC",
  "title": ":{unav)",
  "URL": "http://bmcgenomics.biomedcentral.com/articles/10.1186/1471-2164-7-187"
}
```

The `title` gets the rather bizarre value of `:{unav)`. Is it because Crossref [returns](http://api.crossref.org/works/10.1186/1471-2164-7-187) the title as an array?

```json
    "title": [
      "Finding function: evaluation methods for functional genomic data"
    ],
```

Thanks Manubot user @miltondp for reporting the downstream consequences of this problem.

**Comment by mfenner** [comment]
The issue is fixed and the content negotiation service at data.crosscite.org will be updated tomorrow.

**Comment by mfenner** [comment]
The Citeproc JSON metadata for this DOI now look good. If there are still issues with other DOIs, it is most likely an issue with the metadata import and conversion from Crossref, not a content negotiation issue.

**Comment by dhimmel** [comment]
Thanks @mfenner. I just checked and can confirm that https://data.crosscite.org/application/vnd.citationstyles.csl+json/10.1186/1471-2164-7-187 now returns:

```json
  "title": "Finding function: evaluation methods for functional genomic data",
```

Nice to see https://github.com/datacite/bolognese/commit/e21c858411db610d48365c653cf262b0c2a5235f and https://github.com/crosscite/content-negotiation/commit/7146efd68ed902e3839fcefa6aa45cec7c285589 to help me understand the awesome infrastructure behind crosscite content-negotiation.

**Comment by mfenner** [comment]
Thanks @dhimmel. You may also like https://github.com/datacite/bolognese/commit/b122b37d7b515ea32279682be1cbb35da27ab41a that I pushed just now for bolognese `1.8.13`, providing support for article id if no page numbers are provided.
