### ISSUE TITLE
Incomplete Metadata retrieval when asking for application/vnd.datacite.datacite+xml/

### ISSUE THREAD

**Issue by kjgarza** [crosscite/content-negotiation#2]
Caching in different content format is breaking CN XML request

To add logic to bypass caching on application/vnd.datacite.datacite+xml content

**Comment by mfenner** [comment]
The index_controller should have this line to initialize model:

      @metadata = Metadata.new(input: @id, from: from, format: format)

And both from and format defines in the controller before the call. For from use 

    from = Bolognese.find_from_format(id: @id)

**Comment by mfenner** [comment]
In metadata model change line to

    return super(input: input) if from == format || %w(test).include?(Rails.env)

**Comment by kjgarza** [comment]
Fixed with commit c0220b4425275e3457158d8926c721ac095f26a1
