### ISSUE TITLE
#6359 Re: text bibtex export incorrect

### ISSUE THREAD

**Issue by kjgarza** [crosscite/content-negotiation#46]
I think there is another bug with the bibtex output. Several items don't give any bibtex output at all, even though there is RIS, JATS, etc. output. See for example:

https://data.datacite.org/application/x-bibtex/10.6084/m9.figshare.1050137 

https://data.datacite.org/application/x-bibtex/10.6084/m9.figshare.1050137.v1 

https://data.datacite.org/application/x-bibtex/10.7925/drs1.duchas_4510309

**Comment by mfenner** [comment]
This has been fixed with the latest version.
