### ISSUE TITLE
Page/article number missing

### ISSUE THREAD

**Issue by giovannipizzi** [crosscite/content-negotiation#96]
If I run `curl -LH "Accept: application/x-bibtex" https://data.datacite.org/10.1103%2Fphysrevlett.120.117701` I get:
```bibtex
@article{https://doi.org/10.1103/physrevlett.120.117701,
  doi = {10.1103/physrevlett.120.117701},
  url = {https://link.aps.org/doi/10.1103/PhysRevLett.120.117701},
  author = {Marrazzo, Antimo and Gibertini, Marco and Campi, Davide and Mounet, Nicolas and Marzari, Nicola},
  title = {Prediction of a Large-Gap and Switchable Kane-Mele Quantum Spin Hall Insulator},
  journal = {Physical Review Letters},
  volume = {120},
  issue = {11},
  publisher = {American Physical Society (APS)},
  year = {2018}
}
```
where there is neither the page number nor the article ID (117701), so I do not get enough information to do a proper full citation.

This happens with essentially all articles of some journals that do not use page numbers but article IDs, like PRL above, but I also see with other journals, e.g. Nature Communications.

Is this a known issue?

P.S.: I hope this is the correct repository where to post this issue

**Comment by giovannipizzi** [comment]
Thanks a lot @mfenner !
Do you know when this will be deployed on https://data.datacite.org?

**Comment by mfenner** [comment]
It is already deployed at data.crosscite.org. data.datacite.org is an alias for it.

**Comment by giovannipizzi** [comment]
Ah ok thanks - however (maybe caching?) I still get only this:
`curl -LH "Accept: application/x-bibtex" https://data.datacite.org/10.1103%2Fphysrevlett.120.117701`

```
@article{https://doi.org/10.1103/physrevlett.120.117701,
  doi = {10.1103/PHYSREVLETT.120.117701},
  url = {https://link.aps.org/doi/10.1103/PhysRevLett.120.117701},
  author = {Marrazzo, Antimo and Gibertini, Marco and Campi, Davide and Mounet, Nicolas and Marzari, Nicola},
  title = {Prediction of a Large-Gap and Switchable Kane-Mele Quantum Spin Hall Insulator},
  journal = {Physical Review Letters},
  volume = {120},
  issue = {11},
  publisher = {American Physical Society (APS)},
  year = {2018}
}
```
without the article ID 117701... (or am I missing something?)

**Comment by mfenner** [comment]
@giovannipizzi I double-checked and there is another issue here that complicates things: we have started to import Crossref DOIs into our search index and that includes `10.1103/PhysRevLett.120.117701`, see for example https://commons.datacite.org/doi.org/10.1103/physrevlett.120.117701. This means that we also have to update the metadata we store internally to make this work. But this should work for any Crossref DOI not stored by us.

**Comment by mfenner** [comment]
This is now fixed for this specific DOI, using your curl command:

```
@article{https://doi.org/10.1103/physrevlett.120.117701,
  doi = {10.1103/PHYSREVLETT.120.117701},
  url = {https://link.aps.org/doi/10.1103/PhysRevLett.120.117701},
  author = {Marrazzo, Antimo and Gibertini, Marco and Campi, Davide and Mounet, Nicolas and Marzari, Nicola},
  title = {Prediction of a Large-Gap and Switchable Kane-Mele Quantum Spin Hall Insulator},
  journal = {Physical Review Letters},
  volume = {120},
  issue = {11},
  pages = {117701},
  publisher = {American Physical Society (APS)},
  year = {2018}
}
```

**Comment by giovannipizzi** [comment]
Thanks!
